name: "gin_scaffold"
mode: "release"
port: 8088
version: "v0.0.1"
start_time: "2022-03-25"
machine_id: 1

log:
  level: "info"
  filename: "gin_scaffold.log"
  max_size: 10
  max_age: 30
  max_backups: 7
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "P@ssw0rd"
  dbname: "gintest"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100